tasks:
  - name: clone
    taskRef:
      name: git-clone
    workspaces:
      - name: output
        workspace: pipeline-workspace

  - name: npminstall
    runAfter:
      - clone
    taskRef:
      name: npm
    workspaces:
      - name: source
        workspace: pipeline-workspace

  - name: tests
    runAfter:
      - npminstall
    taskRef:
      name: jasmine
    workspaces:
      - name: source
        workspace: pipeline-workspace

  - name: build
    runAfter:
      - tests
    taskRef:
      kind: ClusterTask
      name: buildah
    params:
      - name: IMAGE
        value: $(params.build-image)
    workspaces:
      - name: source
        workspace: pipeline-workspace
      - name: dockerconfig
        workspace: dockerconfig-ws